name: Test

on: push

jobs:
  test:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Install requirements
        run: sudo apt-get install libzmq3-dev -y

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: ./scripts/build.sh

      - name: Test
        run: go test ./... -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
